# Site settings
title: Not By Default
email: team@notbydefault.co
description: > # this means to ignore newlines until "baseurl:"
  We're here to create a community for students trying to "figure it all out."
  For students, from students: to inspire, support, and challenge each other 
  to seek a path that is right for each individual --  and to do so 
  deliberately, with excitement, and **not by default**.
baseurl: "/NBD" # the subpath of your site, e.g. /blog/
url: "http://notbydefault.co" # the base hostname & protocol for your site
twitter_username: notbydefaultco

# Build settings
markdown: kramdown
